### ISSUE TITLE
Allow to pass broker address/config though URL

### ISSUE THREAD

**Issue by jonnor** [msgflo/msgflo-browser#3]
Analogous to the `MSGFLO_BROKER` envvar, the browser code should respect a `msgflo_broker` query parameter.

**Comment by bergie** [comment]
There is now the `msgflo.options` helper for this, as seen in the infodisplay example:

```javascript
var params = msgflo.options({
  broker: 'mqtt://localhost',
  role: 'infodisplay'
});
var p = DisplayParticipant(params.broker, params.role);
```
